/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agmanager.ui;

import agmanager.out.terminal.OutputTerminal;
import agmanager.ui.button.RunButton;
import agmanager.ui.button.SaveButton;
import agmanager.out.image.OutputImage;

/**
 *
 * @author 悠也
 */
public class AgentManagerUI extends javax.swing.JFrame {

    /**
     * Creates new form AgentManageUI
     */
    public AgentManagerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMainTabPanel = new javax.swing.JPanel();
        jMainPanel = new javax.swing.JPanel();
        jExplainLabel2 = new javax.swing.JLabel();
        jClassPanel = new javax.swing.JPanel();
        jTitleLabel6 = new javax.swing.JLabel();
        jClassComboBox = new javax.swing.JComboBox();
        jSWUniOrMultiButton = new javax.swing.JButton();
        jTitleLabel9 = new javax.swing.JLabel();
        jTryTextField = new javax.swing.JTextField();
        jAgentTypePanel = new javax.swing.JPanel();
        jTitleLabel7 = new javax.swing.JLabel();
        jAgentTypeComboBox = new javax.swing.JComboBox();
        jPartitioningComboBox = new javax.swing.JComboBox();
        jTitleLabel10 = new javax.swing.JLabel();
        jDataTypePanel = new javax.swing.JPanel();
        jTitleLabel8 = new javax.swing.JLabel();
        jDataTypeComboBox = new javax.swing.JComboBox();
        jTimeTextField = new javax.swing.JTextField();
        jTitleLabel11 = new javax.swing.JLabel();
        jTestPanel = new javax.swing.JPanel();
        jExplainLabel1 = new javax.swing.JLabel();
        jRunCheckLabel = new javax.swing.JLabel();
        jCretaePanel = new javax.swing.JPanel();
        jTitleLabel1 = new javax.swing.JLabel();
        jCreateClassComboBox = new javax.swing.JComboBox();
        jRunCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTitleLabel12 = new javax.swing.JLabel();
        jUpdatePanel = new javax.swing.JPanel();
        jTitleLabel2 = new javax.swing.JLabel();
        jUpdateClassComboBox = new javax.swing.JComboBox();
        jRunCheckBox2 = new javax.swing.JCheckBox();
        jReadPanel = new javax.swing.JPanel();
        jTitleLabel3 = new javax.swing.JLabel();
        jReadClassComboBox = new javax.swing.JComboBox();
        jRunCheckBox3 = new javax.swing.JCheckBox();
        jDeletePanel = new javax.swing.JPanel();
        jTitleLabel4 = new javax.swing.JLabel();
        jDeleteClassComboBox = new javax.swing.JComboBox();
        jRunCheckBox4 = new javax.swing.JCheckBox();
        jLoadPanel = new javax.swing.JPanel();
        jTitleLabel5 = new javax.swing.JLabel();
        jLoadClassComboBox = new javax.swing.JComboBox();
        jRunCheckBox5 = new javax.swing.JCheckBox();
        jWDirectoryLabel = new javax.swing.JLabel();
        jWDirectoryTextField = new javax.swing.JTextField();
        jControlPanel = new javax.swing.JPanel();
        jCancelButton = new javax.swing.JButton();
        jRunButton = new javax.swing.JButton();
        jRunRadioButton = new javax.swing.JRadioButton();
        jTestRadioButton = new javax.swing.JRadioButton();
        jLogCheckBox = new javax.swing.JCheckBox();
        jServerTabPanel = new javax.swing.JPanel();
        jFilePathLabel = new javax.swing.JLabel();
        jFilePathTextField = new javax.swing.JTextField();
        jPropertyScrollPane = new javax.swing.JScrollPane();
        jPropertyTextPane = new javax.swing.JTextPane();
        jSaveButton = new javax.swing.JButton();
        jAgentTabPanel = new javax.swing.JPanel();
        jFilePathLabel1 = new javax.swing.JLabel();
        jFilePathTextField1 = new javax.swing.JTextField();
        jPropertyScrollPane1 = new javax.swing.JScrollPane();
        jPropertyTextPane1 = new javax.swing.JTextPane();
        jSaveButton1 = new javax.swing.JButton();
        jQueueTabPanel = new javax.swing.JPanel();
        jFilePathLabel2 = new javax.swing.JLabel();
        jFilePathTextField2 = new javax.swing.JTextField();
        jPropertyScrollPane2 = new javax.swing.JScrollPane();
        jPropertyTextPane2 = new javax.swing.JTextPane();
        jSaveButton2 = new javax.swing.JButton();
        jLogTabPanel = new javax.swing.JPanel();
        jLogFilePanel = new javax.swing.JPanel();
        jLogDirectoryLabel = new javax.swing.JLabel();
        jLogDirectoryTextField = new javax.swing.JTextField();
        jFileFormatLabel = new javax.swing.JLabel();
        jFileFormatTextField = new javax.swing.JTextField();
        jFileTypeSpinner = new javax.swing.JSpinner();
        jFileTypeLabel = new javax.swing.JLabel();
        jLogFormatScrollPane = new javax.swing.JScrollPane();
        jLogFormatTextArea = new javax.swing.JTextArea();
        jExplainLabel3 = new javax.swing.JLabel();
        jSaveButton3 = new javax.swing.JButton();
        jLogFilePanel1 = new javax.swing.JPanel();
        jLogDirectoryLabel1 = new javax.swing.JLabel();
        jLogDirectoryTextField1 = new javax.swing.JTextField();
        jFileFormatLabel1 = new javax.swing.JLabel();
        jFileFormatTextField1 = new javax.swing.JTextField();
        jFileTypeSpinner1 = new javax.swing.JSpinner();
        jFileTypeLabel1 = new javax.swing.JLabel();
        jLogFormatScrollPane1 = new javax.swing.JScrollPane();
        jLogFormatTextArea1 = new javax.swing.JTextArea();
        jExplainLabel4 = new javax.swing.JLabel();
        jLog2EnabeleCheckBox = new javax.swing.JCheckBox();
        jSplitPane1 = new javax.swing.JSplitPane();
        jOutputToggleButton = new javax.swing.JToggleButton();
        jOutputImageToggleButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Main", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century", 1, 12))); // NOI18N

        jExplainLabel2.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jExplainLabel2.setText("jLabel8");

        jClassPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTitleLabel6.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jTitleLabel6.setText("Class:");

        jClassComboBox.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jClassComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jSWUniOrMultiButton.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jSWUniOrMultiButton.setText("UNI");

        jTitleLabel9.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jTitleLabel9.setText("try:");

        jTryTextField.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jTryTextField.setText("1");

        javax.swing.GroupLayout jClassPanelLayout = new javax.swing.GroupLayout(jClassPanel);
        jClassPanel.setLayout(jClassPanelLayout);
        jClassPanelLayout.setHorizontalGroup(
            jClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jClassPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitleLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTitleLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTryTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSWUniOrMultiButton)
                .addGap(7, 7, 7))
        );
        jClassPanelLayout.setVerticalGroup(
            jClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jSWUniOrMultiButton)
                .addComponent(jClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTitleLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTitleLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addComponent(jTryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jAgentTypePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTitleLabel7.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jTitleLabel7.setText("AgentType:");

        jAgentTypeComboBox.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jAgentTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Agnet Typing", "Agent Cloning" }));

        jPartitioningComboBox.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jPartitioningComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hash", "Range" }));

        jTitleLabel10.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jTitleLabel10.setText("Partitioning:");

        javax.swing.GroupLayout jAgentTypePanelLayout = new javax.swing.GroupLayout(jAgentTypePanel);
        jAgentTypePanel.setLayout(jAgentTypePanelLayout);
        jAgentTypePanelLayout.setHorizontalGroup(
            jAgentTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAgentTypePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitleLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAgentTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTitleLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPartitioningComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jAgentTypePanelLayout.setVerticalGroup(
            jAgentTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAgentTypePanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jAgentTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAgentTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTitleLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPartitioningComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTitleLabel10))
                .addContainerGap())
        );

        jDataTypePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTitleLabel8.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jTitleLabel8.setText("DataType:");

        jDataTypeComboBox.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jDataTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mountain", "Impulse" }));

        jTimeTextField.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jTimeTextField.setText("1");

        jTitleLabel11.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jTitleLabel11.setText("Time:");

        javax.swing.GroupLayout jDataTypePanelLayout = new javax.swing.GroupLayout(jDataTypePanel);
        jDataTypePanel.setLayout(jDataTypePanelLayout);
        jDataTypePanelLayout.setHorizontalGroup(
            jDataTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDataTypePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitleLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDataTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTitleLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDataTypePanelLayout.setVerticalGroup(
            jDataTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTitleLabel8, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jDataTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTitleLabel11)
                .addComponent(jDataTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jMainPanelLayout = new javax.swing.GroupLayout(jMainPanel);
        jMainPanel.setLayout(jMainPanelLayout);
        jMainPanelLayout.setHorizontalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDataTypePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jAgentTypePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jExplainLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jClassPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jMainPanelLayout.setVerticalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addComponent(jExplainLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jClassPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAgentTypePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDataTypePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTestPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Test", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century", 1, 12))); // NOI18N

        jExplainLabel1.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jExplainLabel1.setText("jLabel1");

        jRunCheckLabel.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jRunCheckLabel.setText("Run Checked");

        jCretaePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCretaePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTitleLabel1.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jTitleLabel1.setText("Create:");

        jCreateClassComboBox.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jCreateClassComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField1.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jTextField1.setText("1");

        jTitleLabel12.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jTitleLabel12.setText("Agent N::");

        javax.swing.GroupLayout jCretaePanelLayout = new javax.swing.GroupLayout(jCretaePanel);
        jCretaePanel.setLayout(jCretaePanelLayout);
        jCretaePanelLayout.setHorizontalGroup(
            jCretaePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCretaePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCreateClassComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTitleLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jRunCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jCretaePanelLayout.setVerticalGroup(
            jCretaePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCretaePanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jCretaePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jRunCheckBox1)
                    .addComponent(jCreateClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTitleLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTitleLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jUpdatePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTitleLabel2.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jTitleLabel2.setText("Update:");

        jUpdateClassComboBox.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jUpdateClassComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jUpdatePanelLayout = new javax.swing.GroupLayout(jUpdatePanel);
        jUpdatePanel.setLayout(jUpdatePanelLayout);
        jUpdatePanelLayout.setHorizontalGroup(
            jUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jUpdatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitleLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUpdateClassComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jRunCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jUpdatePanelLayout.setVerticalGroup(
            jUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jUpdatePanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRunCheckBox2)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTitleLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jUpdateClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );

        jReadPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTitleLabel3.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jTitleLabel3.setText("Read  :");

        jReadClassComboBox.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jReadClassComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jReadPanelLayout = new javax.swing.GroupLayout(jReadPanel);
        jReadPanel.setLayout(jReadPanelLayout);
        jReadPanelLayout.setHorizontalGroup(
            jReadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jReadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitleLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jReadClassComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jRunCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jReadPanelLayout.setVerticalGroup(
            jReadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jReadPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jReadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jRunCheckBox3)
                    .addComponent(jReadClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTitleLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDeletePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTitleLabel4.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jTitleLabel4.setText("Delete:");

        jDeleteClassComboBox.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jDeleteClassComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jDeletePanelLayout = new javax.swing.GroupLayout(jDeletePanel);
        jDeletePanel.setLayout(jDeletePanelLayout);
        jDeletePanelLayout.setHorizontalGroup(
            jDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDeletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitleLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDeleteClassComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jRunCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDeletePanelLayout.setVerticalGroup(
            jDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDeletePanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jRunCheckBox4)
                    .addComponent(jDeleteClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTitleLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLoadPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTitleLabel5.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jTitleLabel5.setText("Load  :");

        jLoadClassComboBox.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jLoadClassComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jLoadPanelLayout = new javax.swing.GroupLayout(jLoadPanel);
        jLoadPanel.setLayout(jLoadPanelLayout);
        jLoadPanelLayout.setHorizontalGroup(
            jLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitleLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLoadClassComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jRunCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLoadPanelLayout.setVerticalGroup(
            jLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoadPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLoadClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTitleLabel5)
                    .addComponent(jRunCheckBox5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jTestPanelLayout = new javax.swing.GroupLayout(jTestPanel);
        jTestPanel.setLayout(jTestPanelLayout);
        jTestPanelLayout.setHorizontalGroup(
            jTestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTestPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jTestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCretaePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addGroup(jTestPanelLayout.createSequentialGroup()
                        .addComponent(jExplainLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRunCheckLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jUpdatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(jReadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(jDeletePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLoadPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jTestPanelLayout.setVerticalGroup(
            jTestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTestPanelLayout.createSequentialGroup()
                .addGroup(jTestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jExplainLabel1)
                    .addComponent(jRunCheckLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCretaePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUpdatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jReadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDeletePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLoadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jWDirectoryLabel.setText("Working Directory:");

        jCancelButton.setText("Cancel");

        jRunButton.setText("Run");
        jRunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRunButtonActionPerformed(evt);
            }
        });

        selectButtonGroup.add(jRunRadioButton);
        jRunRadioButton.setText("Main");

        selectButtonGroup.add(jTestRadioButton);
        jTestRadioButton.setText("Test");

        jLogCheckBox.setText("Log");

        javax.swing.GroupLayout jControlPanelLayout = new javax.swing.GroupLayout(jControlPanel);
        jControlPanel.setLayout(jControlPanelLayout);
        jControlPanelLayout.setHorizontalGroup(
            jControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTestRadioButton)
                .addGap(18, 18, 18)
                .addComponent(jRunRadioButton)
                .addGap(35, 35, 35)
                .addComponent(jLogCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jControlPanelLayout.setVerticalGroup(
            jControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTestRadioButton)
                    .addComponent(jRunRadioButton)
                    .addComponent(jRunButton)
                    .addComponent(jCancelButton)
                    .addComponent(jLogCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jMainTabPanelLayout = new javax.swing.GroupLayout(jMainTabPanel);
        jMainTabPanel.setLayout(jMainTabPanelLayout);
        jMainTabPanelLayout.setHorizontalGroup(
            jMainTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jMainTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTestPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jMainTabPanelLayout.createSequentialGroup()
                        .addComponent(jWDirectoryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jWDirectoryTextField))
                    .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jMainTabPanelLayout.setVerticalGroup(
            jMainTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jMainTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jWDirectoryLabel)
                    .addComponent(jWDirectoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTestPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Main", jMainTabPanel);

        jFilePathLabel.setText("FilePath:");

        jFilePathTextField.setText("server.property");

        jPropertyTextPane.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jPropertyScrollPane.setViewportView(jPropertyTextPane);

        jSaveButton.setText("Save");
        jSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jServerTabPanelLayout = new javax.swing.GroupLayout(jServerTabPanel);
        jServerTabPanel.setLayout(jServerTabPanelLayout);
        jServerTabPanelLayout.setHorizontalGroup(
            jServerTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jServerTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jServerTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPropertyScrollPane)
                    .addGroup(jServerTabPanelLayout.createSequentialGroup()
                        .addComponent(jFilePathLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFilePathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jServerTabPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSaveButton)))
                .addContainerGap())
        );
        jServerTabPanelLayout.setVerticalGroup(
            jServerTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jServerTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jServerTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFilePathLabel)
                    .addComponent(jFilePathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPropertyScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSaveButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Server", jServerTabPanel);

        jFilePathLabel1.setText("FilePath:");

        jFilePathTextField1.setText("agent.property");

        jPropertyTextPane1.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jPropertyScrollPane1.setViewportView(jPropertyTextPane1);

        jSaveButton1.setText("Save");
        jSaveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jAgentTabPanelLayout = new javax.swing.GroupLayout(jAgentTabPanel);
        jAgentTabPanel.setLayout(jAgentTabPanelLayout);
        jAgentTabPanelLayout.setHorizontalGroup(
            jAgentTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAgentTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jAgentTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPropertyScrollPane1)
                    .addGroup(jAgentTabPanelLayout.createSequentialGroup()
                        .addComponent(jFilePathLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFilePathTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAgentTabPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSaveButton1)))
                .addContainerGap())
        );
        jAgentTabPanelLayout.setVerticalGroup(
            jAgentTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAgentTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jAgentTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFilePathLabel1)
                    .addComponent(jFilePathTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPropertyScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSaveButton1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agent", jAgentTabPanel);

        jFilePathLabel2.setText("FilePath:");

        jFilePathTextField2.setText("queue.property");

        jPropertyTextPane2.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jPropertyScrollPane2.setViewportView(jPropertyTextPane2);

        jSaveButton2.setText("Save");
        jSaveButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jQueueTabPanelLayout = new javax.swing.GroupLayout(jQueueTabPanel);
        jQueueTabPanel.setLayout(jQueueTabPanelLayout);
        jQueueTabPanelLayout.setHorizontalGroup(
            jQueueTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jQueueTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jQueueTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPropertyScrollPane2)
                    .addGroup(jQueueTabPanelLayout.createSequentialGroup()
                        .addComponent(jFilePathLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFilePathTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jQueueTabPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSaveButton2)))
                .addContainerGap())
        );
        jQueueTabPanelLayout.setVerticalGroup(
            jQueueTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jQueueTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jQueueTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFilePathLabel2)
                    .addComponent(jFilePathTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPropertyScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSaveButton2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Queue", jQueueTabPanel);

        jLogFilePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Log1"));

        jLogDirectoryLabel.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jLogDirectoryLabel.setText("Log Directory:");

        jLogDirectoryTextField.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N

        jFileFormatLabel.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jFileFormatLabel.setText("File Format  :");

        jFileFormatTextField.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jFileFormatTextField.setText("Log_\"yyyymmdd\"_\"hhmmss\"_\"testclass1\"");

        jFileTypeSpinner.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jFileTypeSpinner.setModel(new javax.swing.SpinnerListModel(new String[] {"TXT", "CSV", "LOG"}));

        jFileTypeLabel.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jFileTypeLabel.setText("File Type:");

        jLogFormatTextArea.setColumns(20);
        jLogFormatTextArea.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLogFormatTextArea.setRows(5);
        jLogFormatScrollPane.setViewportView(jLogFormatTextArea);

        jExplainLabel3.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jExplainLabel3.setText("jLabel1");

        javax.swing.GroupLayout jLogFilePanelLayout = new javax.swing.GroupLayout(jLogFilePanel);
        jLogFilePanel.setLayout(jLogFilePanelLayout);
        jLogFilePanelLayout.setHorizontalGroup(
            jLogFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLogFilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLogFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLogFilePanelLayout.createSequentialGroup()
                        .addGroup(jLogFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLogFormatScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLogFilePanelLayout.createSequentialGroup()
                                .addGroup(jLogFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLogDirectoryLabel)
                                    .addComponent(jFileFormatLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLogFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jLogFilePanelLayout.createSequentialGroup()
                                        .addComponent(jFileFormatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFileTypeLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFileTypeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLogDirectoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 17, 17))
                    .addGroup(jLogFilePanelLayout.createSequentialGroup()
                        .addComponent(jExplainLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jLogFilePanelLayout.setVerticalGroup(
            jLogFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLogFilePanelLayout.createSequentialGroup()
                .addComponent(jExplainLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLogFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLogDirectoryLabel)
                    .addComponent(jLogDirectoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLogFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFileFormatLabel)
                    .addComponent(jFileFormatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFileTypeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFileTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLogFormatScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSaveButton3.setText("Save");
        jSaveButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveButton3ActionPerformed(evt);
            }
        });

        jLogFilePanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Log2"));

        jLogDirectoryLabel1.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jLogDirectoryLabel1.setText("Log Directory:");

        jLogDirectoryTextField1.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N

        jFileFormatLabel1.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jFileFormatLabel1.setText("File Format  :");

        jFileFormatTextField1.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jFileFormatTextField1.setText("Log_\"yyyymmdd\"_\"hhmmss\"_\"class\"");

        jFileTypeSpinner1.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jFileTypeSpinner1.setModel(new javax.swing.SpinnerListModel(new String[] {"TXT", "CSV", "LOG"}));

        jFileTypeLabel1.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jFileTypeLabel1.setText("File Type:");

        jLogFormatTextArea1.setColumns(20);
        jLogFormatTextArea1.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLogFormatTextArea1.setRows(5);
        jLogFormatScrollPane1.setViewportView(jLogFormatTextArea1);

        jExplainLabel4.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N
        jExplainLabel4.setText("jLabel1");

        jLog2EnabeleCheckBox.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N

        javax.swing.GroupLayout jLogFilePanel1Layout = new javax.swing.GroupLayout(jLogFilePanel1);
        jLogFilePanel1.setLayout(jLogFilePanel1Layout);
        jLogFilePanel1Layout.setHorizontalGroup(
            jLogFilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLogFilePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLogFilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLogFilePanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLog2EnabeleCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jExplainLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jLogFilePanel1Layout.createSequentialGroup()
                        .addComponent(jLogFormatScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jLogFilePanel1Layout.createSequentialGroup()
                        .addComponent(jLogDirectoryLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLogDirectoryTextField1))
                    .addGroup(jLogFilePanel1Layout.createSequentialGroup()
                        .addGroup(jLogFilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLogFilePanel1Layout.createSequentialGroup()
                                .addComponent(jFileFormatLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFileFormatTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFileTypeLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLogFilePanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jFileTypeSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)))
                .addContainerGap())
        );
        jLogFilePanel1Layout.setVerticalGroup(
            jLogFilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLogFilePanel1Layout.createSequentialGroup()
                .addGroup(jLogFilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jExplainLabel4)
                    .addComponent(jLog2EnabeleCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLogFilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLogDirectoryLabel1)
                    .addComponent(jLogDirectoryTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLogFilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFileFormatLabel1)
                    .addComponent(jFileFormatTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFileTypeSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFileTypeLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLogFormatScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jLogTabPanelLayout = new javax.swing.GroupLayout(jLogTabPanel);
        jLogTabPanel.setLayout(jLogTabPanelLayout);
        jLogTabPanelLayout.setHorizontalGroup(
            jLogTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLogTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLogTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLogTabPanelLayout.createSequentialGroup()
                        .addGap(0, 324, Short.MAX_VALUE)
                        .addComponent(jSaveButton3))
                    .addGroup(jLogTabPanelLayout.createSequentialGroup()
                        .addGroup(jLogTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLogFilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLogFilePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLogTabPanelLayout.setVerticalGroup(
            jLogTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLogTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLogFilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLogFilePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(jSaveButton3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Log", jLogTabPanel);

        jSplitPane1.setDividerLocation(290);
        jSplitPane1.setDividerSize(2);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setFont(new java.awt.Font("MS UI Gothic", 0, 10)); // NOI18N

        jOutputToggleButton.setFont(new java.awt.Font("MS UI Gothic", 1, 10)); // NOI18N
        jOutputToggleButton.setText(">");
        jOutputToggleButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jOutputToggleButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jOutputToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOutputToggleButtonActionPerformed(evt);
            }
        });
        jSplitPane1.setLeftComponent(jOutputToggleButton);

        jOutputImageToggleButton.setFont(new java.awt.Font("MS UI Gothic", 1, 10)); // NOI18N
        jOutputImageToggleButton.setText(">");
        jOutputImageToggleButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jOutputImageToggleButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jOutputImageToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOutputImageToggleButtonActionPerformed(evt);
            }
        });
        jSplitPane1.setRightComponent(jOutputImageToggleButton);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jSplitPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Server Tab SaveButton
    private void jSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveButtonActionPerformed
        // TODO add your handling code here:
        SaveButton agSave = new SaveButton(jFilePathTextField.getText());
        agSave.execute(jPropertyTextPane.getText());
    }//GEN-LAST:event_jSaveButtonActionPerformed

    //Agent Tab SaveButton
    private void jSaveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveButton1ActionPerformed
        // TODO add your handling code here:
        SaveButton agSave = new SaveButton(jFilePathTextField1.getText());
        agSave.execute(jPropertyTextPane1.getText());
    }//GEN-LAST:event_jSaveButton1ActionPerformed

    //Queue Tab SaveButton
    private void jSaveButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveButton2ActionPerformed
        // TODO add your handling code here:
        SaveButton agSave = new SaveButton(jFilePathTextField2.getText());
        agSave.execute(jPropertyTextPane2.getText());
    }//GEN-LAST:event_jSaveButton2ActionPerformed

    //Log Tab SaveButton
    private void jSaveButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveButton3ActionPerformed
        // TODO add your handling code here:
        SaveButton agSave = new SaveButton("log.ini");
        
        StringBuilder logtext = new StringBuilder();
        
        String name = "Log1";
        logtext.append(name+"="+"true"+"\n");
        logtext.append(name+"."+"directory" +"="+ jLogDirectoryTextField.getText()+"\n");
        logtext.append(name+"."+"format"+"="+jFileFormatTextField.getText()+"\n");
        logtext.append(name+"."+"type"+"="+jFileTypeSpinner.getModel().getValue()+"\n");
        logtext.append(name+".col"+"="+jLogFormatTextArea.getText().split("\n").length+"\n");
        int i = 0;
        for(String line : jLogFormatTextArea.getText().split("\n")){
            if(line != ""){
                logtext.append(name+"."+i+"="+line+"\n");
                i++;
            }
        }
        
        name = "Log2";
        if(jLog2EnabeleCheckBox.isSelected())
            logtext.append(name+"="+"true"+"\n");
        else
            logtext.append(name+"="+"false"+"\n");
        logtext.append(name+"."+"directory" +"="+ jLogDirectoryTextField1.getText()+"\n");
        logtext.append(name+"."+"format"+"="+jFileFormatTextField1.getText()+"\n");
        logtext.append(name+"."+"type"+"="+jFileTypeSpinner1.getModel().getValue()+"\n");
        logtext.append(name+".col"+"="+jLogFormatTextArea1.getText().split("\n").length+"\n");
        i = 0;
        for(String line : jLogFormatTextArea1.getText().split("\n")){
            if(line != ""){
                logtext.append(name+"."+i+"="+line+"\n");
                i++;
            }
        }
        
        agSave.execute(logtext.toString());
    }//GEN-LAST:event_jSaveButton3ActionPerformed

    private static OutputTerminal terminal;
    private void jOutputToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOutputToggleButtonActionPerformed
        // TODO add your handling code here:
        if(jOutputToggleButton.isSelected()){
            terminal.setBounds(this.getX()+this.getWidth(), this.getY(), 740, this.getHeight());
            terminal.setVisible(true);
        }
        else{
            terminal.setVisible(false);
        }
    }//GEN-LAST:event_jOutputToggleButtonActionPerformed

    private void jRunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRunButtonActionPerformed
        // TODO add your handling code here:
        RunButton r = new RunButton();
        r.command();
    }//GEN-LAST:event_jRunButtonActionPerformed

    private static OutputImage image;
    private void jOutputImageToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOutputImageToggleButtonActionPerformed
        // TODO add your handling code here:
        if(jOutputImageToggleButton.isSelected()){
            image.setBounds(this.getX()+this.getWidth(), this.getY(), 740, this.getHeight());
            image.setVisible(true);
        }
        else{
            image.setVisible(false);
        }
    }//GEN-LAST:event_jOutputImageToggleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentManagerUI().setVisible(true);
                
                terminal = OutputTerminal.getTerminal();
                image = OutputImage.getImage();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jAgentTabPanel;
    private javax.swing.JComboBox jAgentTypeComboBox;
    private javax.swing.JPanel jAgentTypePanel;
    private javax.swing.JButton jCancelButton;
    private javax.swing.JComboBox jClassComboBox;
    private javax.swing.JPanel jClassPanel;
    private javax.swing.JPanel jControlPanel;
    private javax.swing.JComboBox jCreateClassComboBox;
    private javax.swing.JPanel jCretaePanel;
    private javax.swing.JComboBox jDataTypeComboBox;
    private javax.swing.JPanel jDataTypePanel;
    private javax.swing.JComboBox jDeleteClassComboBox;
    private javax.swing.JPanel jDeletePanel;
    private javax.swing.JLabel jExplainLabel1;
    private javax.swing.JLabel jExplainLabel2;
    private javax.swing.JLabel jExplainLabel3;
    private javax.swing.JLabel jExplainLabel4;
    private javax.swing.JLabel jFileFormatLabel;
    private javax.swing.JLabel jFileFormatLabel1;
    private javax.swing.JTextField jFileFormatTextField;
    private javax.swing.JTextField jFileFormatTextField1;
    private javax.swing.JLabel jFilePathLabel;
    private javax.swing.JLabel jFilePathLabel1;
    private javax.swing.JLabel jFilePathLabel2;
    private javax.swing.JTextField jFilePathTextField;
    private javax.swing.JTextField jFilePathTextField1;
    private javax.swing.JTextField jFilePathTextField2;
    private javax.swing.JLabel jFileTypeLabel;
    private javax.swing.JLabel jFileTypeLabel1;
    private javax.swing.JSpinner jFileTypeSpinner;
    private javax.swing.JSpinner jFileTypeSpinner1;
    private javax.swing.JComboBox jLoadClassComboBox;
    private javax.swing.JPanel jLoadPanel;
    private javax.swing.JCheckBox jLog2EnabeleCheckBox;
    private javax.swing.JCheckBox jLogCheckBox;
    private javax.swing.JLabel jLogDirectoryLabel;
    private javax.swing.JLabel jLogDirectoryLabel1;
    private javax.swing.JTextField jLogDirectoryTextField;
    private javax.swing.JTextField jLogDirectoryTextField1;
    private javax.swing.JPanel jLogFilePanel;
    private javax.swing.JPanel jLogFilePanel1;
    private javax.swing.JScrollPane jLogFormatScrollPane;
    private javax.swing.JScrollPane jLogFormatScrollPane1;
    private javax.swing.JTextArea jLogFormatTextArea;
    private javax.swing.JTextArea jLogFormatTextArea1;
    private javax.swing.JPanel jLogTabPanel;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JPanel jMainTabPanel;
    private javax.swing.JToggleButton jOutputImageToggleButton;
    private javax.swing.JToggleButton jOutputToggleButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jPartitioningComboBox;
    private javax.swing.JScrollPane jPropertyScrollPane;
    private javax.swing.JScrollPane jPropertyScrollPane1;
    private javax.swing.JScrollPane jPropertyScrollPane2;
    private javax.swing.JTextPane jPropertyTextPane;
    private javax.swing.JTextPane jPropertyTextPane1;
    private javax.swing.JTextPane jPropertyTextPane2;
    private javax.swing.JPanel jQueueTabPanel;
    private javax.swing.JComboBox jReadClassComboBox;
    private javax.swing.JPanel jReadPanel;
    private javax.swing.JButton jRunButton;
    private javax.swing.JCheckBox jRunCheckBox1;
    private javax.swing.JCheckBox jRunCheckBox2;
    private javax.swing.JCheckBox jRunCheckBox3;
    private javax.swing.JCheckBox jRunCheckBox4;
    private javax.swing.JCheckBox jRunCheckBox5;
    private javax.swing.JLabel jRunCheckLabel;
    private javax.swing.JRadioButton jRunRadioButton;
    private javax.swing.JButton jSWUniOrMultiButton;
    private javax.swing.JButton jSaveButton;
    private javax.swing.JButton jSaveButton1;
    private javax.swing.JButton jSaveButton2;
    private javax.swing.JButton jSaveButton3;
    private javax.swing.JPanel jServerTabPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jTestPanel;
    private javax.swing.JRadioButton jTestRadioButton;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTimeTextField;
    private javax.swing.JLabel jTitleLabel1;
    private javax.swing.JLabel jTitleLabel10;
    private javax.swing.JLabel jTitleLabel11;
    private javax.swing.JLabel jTitleLabel12;
    private javax.swing.JLabel jTitleLabel2;
    private javax.swing.JLabel jTitleLabel3;
    private javax.swing.JLabel jTitleLabel4;
    private javax.swing.JLabel jTitleLabel5;
    private javax.swing.JLabel jTitleLabel6;
    private javax.swing.JLabel jTitleLabel7;
    private javax.swing.JLabel jTitleLabel8;
    private javax.swing.JLabel jTitleLabel9;
    private javax.swing.JTextField jTryTextField;
    private javax.swing.JComboBox jUpdateClassComboBox;
    private javax.swing.JPanel jUpdatePanel;
    private javax.swing.JLabel jWDirectoryLabel;
    private javax.swing.JTextField jWDirectoryTextField;
    private javax.swing.ButtonGroup selectButtonGroup;
    // End of variables declaration//GEN-END:variables
}
